3 different application scripts to create animations from Ansys SPEOS.
ansys/optical-automation pull request #115
Opened 2022-11-21 14:20 UTC by pluAtAnsys

- application script: example_VRLab_animation.py
this script allows users to use a timeline csv file to control the light source in a immersive result. 
the timeline csv file should be in the same format as xmp viewer animation function.

- application script: example_speos_animation.py
this script allow users to define create a series of speos simulation export based on the focus point + sensor trajectory + frame rate.

- application script: rotation_study.py
this script allow users to do ambient source 360 rotation study based on the requested horizontal & vertical step length.

2022-11-21 14:21 UTC, pluAtAnsys commented
@BenoitHeraud the second script can be helpful for camera study

2022-11-23 10:24 UTC, StefanThoene requested changes
The unit test for methods should be mandatory from my perspective even if not tested on the test machine

2022-11-23 10:24 UTC, StefanThoene commented on ansys_optical_automation/post_process/dpf_hdri_viewer.py
> +    def set_source_power(self, source, value):
Test for the added methods for the class are missing

2022-11-23 10:24 UTC, StefanThoene commented on ansys_optical_automation/application/rotation_study.py
> +    function to apply rotation light source study and export simulation
Ambient source not general source-> test for ambient source is missing can lead to alot of confusion

2022-11-23 10:24 UTC, StefanThoene commented on ansys_optical_automation/application/example_speos_animation.py
> +    trajectory = GetRootPart().Curves[0]  # to be defined by user selection
maybe use a input helper for this step

2022-11-23 10:24 UTC, StefanThoene commented on ansys_optical_automation/application/example_VRLab_animation.py
> +def animation_run(speos_file, csv_file):
i would suggest that this becomes a method of the HDRI viewer class as it might be quite intersting for everyone

2022-11-23 17:18 UTC, StefanThoene approved these changes
there are still some minor issues

2022-11-23 17:18 UTC, StefanThoene commented on ansys_optical_automation/application/example_speos_animation.py
> +        print("to export")
```suggestion
        simulation.linked_export_simulation()
```

2022-11-23 17:18 UTC, StefanThoene commented on ansys_optical_automation/application/example_speos_animation.py
> +        "Please select a radiane sensor for animation simulation"
```suggestion
        "Please select a radiance sensor for animation simulation"
```

2022-11-23 21:28 UTC, merged