Stack convert to zemax
ansys/optical-automation pull request #94
Opened 2022-10-09 08:06 UTC by mcheng2022

Not sure if I'm correctly creating this pull request. Please let me know if I did it wrong.

2022-10-09 12:46 UTC, pluAtAnsys commented
As suggested by the failed pre-commmit style automation check, please run "pre-commit run -a" at terminal to make sure following Python PEP 8 standard.
In addition, as you have added new function/method to the library, you also need to create unit test cases to make sure your function is covered by test use case, e.g. test to make sure a *.dat file is generated + test to make sure the generated *.dat file is generated with correct content.

2022-10-10 07:25 UTC, mcheng2022 commented
@pluAtAnsys Do you think I can just edit the test_10 you build for the unit test? Or should I create a new one? Thank you.

2022-10-10 07:53 UTC, pluAtAnsys commented
> @pluAtAnsys Do you think I can just edit the test_10 you build for the unit test? Or should I create a new one? Thank you.

yep, please use the test_10 as that is test group for stack related interop.

2022-10-10 10:04 UTC, mcheng2022 commented
> > @pluAtAnsys Do you think I can just edit the test_10 you build for the unit test? Or should I create a new one? Thank you.
> 
> yep, please use the test_10 as that is test group for stack related interop.

Added!

2022-10-10 10:11 UTC, pluAtAnsys requested changes

2022-10-10 10:11 UTC, pluAtAnsys commented on tests/test_10_stack_interop.py
> +    def test_03_stack_speos_generated(self):
```suggestion
    def test_03_stack_zemax_generated(self):
```

2022-10-10 10:29 UTC, pluAtAnsys approved these changes

2022-10-10 10:30 UTC, merged