Application stack convert to speos
ansys/optical-automation pull request #95
Opened 2022-10-09 08:11 UTC by mcheng2022

2022-10-09 12:38 UTC, pluAtAnsys requested changes

2022-10-09 12:38 UTC, pluAtAnsys commented on ansys_optical_automation/application/stack_convert_to_speos.py
> +        raise TypeError(msg)
```suggestion
    if not stack_result_file:
        print("Exit programme, you have not select any files")
        return
```

2022-10-09 12:38 UTC, pluAtAnsys commented on ansys_optical_automation/application/stack_convert_to_speos.py
> +
```suggestion


```

2022-10-09 12:38 UTC, pluAtAnsys commented on ansys_optical_automation/application/stack_convert_to_speos.py
> +
```suggestion


```

2022-10-09 12:38 UTC, pluAtAnsys commented on ansys_optical_automation/application/stack_convert_to_speos.py
> +
As suggested by the failed pre-commmit style automation check, please run "pre-commit run -a" at terminal to make sure following Python PEP 8 standard

2022-10-09 12:38 UTC, pluAtAnsys commented on ansys_optical_automation/application/stack_convert_to_speos.py
> +
As suggested by the failed pre-commmit style automation check, please run "pre-commit run -a" at terminal to make sure following Python PEP 8 standard.

2022-10-10 07:46 UTC, pluAtAnsys commented
@mcheng2022 I removed the unnecessary imports

2022-10-10 08:27 UTC, mcheng2022 commented
Thank you! That's weird I don't remember why the "from opcode..." line was added...

2022-10-10 08:45 UTC, pluAtAnsys approved these changes

2022-10-10 08:46 UTC, merged